pipeline{
	agent any
	options{
		buildDiscarder(logRotator(numToKeepStr: '1'))
	}
	tools{
	maven 'apache-maven-3.9.5'
	}
	stages{
		stage('toolBuildStage'){
			steps{
			sh '''
			mvn --version
			'''
			}
		}
	}
}
