pipeline{
	agent any
	stages{
	stage('Example Build'){
	steps{
		echo 'before when condition stage execution'	
	}
		}
	}
	stage('Example Deploy'){
	when {
	branch 'whenCondition'
	}
	steps{
	echo 'after when condition stage execution'
		}
	}

}
